<?php
include '../Conexion.php';
$cn = new Conexion();
$CODIGOPRODUCTO = $_POST['CODIGOPRODUCTO'];
$CODIGOUNITARIO = $_POST['CODIGOUNITARIO'];
$FECHA = $_POST['FECHA'];
$COMENTARIO = $_POST['COMENTARIO'];
$USUARIO = $_POST['USUARIO'];

$cn->Conectar();
$return_arr = array();
$res = $cn->Consulta("UPDATE  MANTENCION SET M_FECHATERMINO='$FECHA', M_COMENTARIO ='$COMENTARIO', M_USUARIODEVOLUCION ='$USUARIO',M_ESTADOMANTENCION=0 WHERE CODIGOPRODUCTO='$CODIGOPRODUCTO' AND CODIGOUNITARIO='$CODIGOUNITARIO'");
$cn->Desconectar();
?>