<?php
include '../Conexion.php';
$cn = new Conexion();
$cn2 = new Conexion();
$CODIGOPRODUCTO=$_POST['CODIGOPRODUCTO'];
$CODIGOUNITARIO = $_POST['CODIGOUNITARIO'];
$FECHA = $_POST['FECHA'];
$DESCRIPCION = $_POST['DESCRIPCION'];
$RESPONSABLE = $_POST['RESPONSABLE'];
$USUARIO = $_POST['USUARIO'];
$cn->Conectar();
$cn2->Conectar();

$res = $cn->Consulta("INSERT INTO MANTENCION(CODIGOMANTENCION,CODIGOPRODUCTO,CODIGOUNITARIO,M_FECHAINICIO,M_DESCRIPCION,M_RESPONSABLE,M_USUARIOENVIO,M_ESTADOMANTENCION) VALUES(NULL,'$CODIGOPRODUCTO',$CODIGOUNITARIO,'$FECHA','$DESCRIPCION','$RESPONSABLE','$USUARIO',1)");

$res2 = $cn2->Consulta("UPDATE PRODUCTO_UNITARIO SET PU_ESTADO='4' WHERE CODIGOUNITARIO='$CODIGOUNITARIO' AND CODIGOPRODUCTO='$CODIGOPRODUCTO'");

$cn->Desconectar();
$cn2->Desconectar();
?>