<?php
include '../Conexion.php';
$cn = new Conexion();
$cn2 = new Conexion();
$CODIGOPERMISO = $_POST['CODIGOPERMISO'];
$PROVEEDOR=$_POST['PROVEEDOR'];
$PRODUCTO=$_POST['PRODUCTO'];
$PERSONAL= $_POST['PERSONAL'];
$OBRA=$_POST['OBRA'];
$BODEGA=$_POST['BODEGA'];
$INFORME= $_POST['INFORME'];
$ADMINISTRACION=$_POST['ADMINISTRACION'];
$LOGIN = $_POST['LOGIN'];
$PASSWORD = $_POST['PASSWORD'];
$NOMBRE = $_POST['NOMBRE'];
$APELLIDO = $_POST['APELLIDO'];
$TELEFONO = $_POST['TELEFONO'];
$EMAIL = $_POST['EMAIL'];



$cn->Conectar();
$res = $cn->Consulta("UPDATE USUARIO SET U_PASSWORD='$PASSWORD', U_NOMBRE='$NOMBRE', U_APELLIDO='$APELLIDO', U_TELEFONO ='$TELEFONO', U_EMAIL ='$EMAIL'  WHERE U_LOGIN='$LOGIN'");

$cn2->Conectar();
$res2 = $cn2->Consulta("UPDATE PERMISO SET PROVEEDOR=$PROVEEDOR, PRODUCTO=$PRODUCTO, PERSONAL=$PERSONAL, OBRA=$OBRA,BODEGA=$BODEGA,INFORMEYGRAFICO=$INFORME,ADMINISTRACION=$ADMINISTRACION  WHERE CODIGOPERMISO='$CODIGOPERMISO'");
$cn2->Desconectar();
$cn->Desconectar();
?>