<?php
include '../Conexion.php';
$cn = new Conexion();
$CODIGO = $_POST['CODIGO'];
$RUT = $_POST['RUT'];
$NUMEROFACTURA = $_POST['NUMEROFACTURA'];
$CANTIDAD = $_POST['CANTIDAD'];
$PRECIO = $_POST['PRECIO'];
$TOTALFACTURA = $_POST['TOTALFACTURA'];
$FECHA = $_POST['FECHA'];
$USUARIO = $_POST['USUARIO'];
$PRECIOTOTAL=$CANTIDAD * $PRECIO;
$cn->Conectar();
$return_arr = array();
$res = $cn->Consulta("INSERT INTO INGRESO_PRODUCTO(CODIGOPRODUCTO,RUT,NUMEROFACTURA,IP_CANTIDAD,IP_PRECIOUNITARIO,IP_PRECIOTOTAL,IP_TOTALFACTURA,IP_FECHA,IP_USUARIO) VALUES('$CODIGO','$RUT','$NUMEROFACTURA',$CANTIDAD,$PRECIO,$PRECIOTOTAL,$TOTALFACTURA,'$FECHA','$USUARIO')");
$cn->Desconectar();
?>